## El método k means

In [1]:
import numpy as np

In [2]:
data = np.random.random(90).reshape(30, 3)
data

array([[0.96473876, 0.3670809 , 0.07567672],
       [0.8025873 , 0.86090604, 0.17030074],
       [0.34740988, 0.04820886, 0.2348888 ],
       [0.84337118, 0.78301657, 0.35647387],
       [0.79636266, 0.31370745, 0.46102899],
       [0.43882079, 0.28282488, 0.82016433],
       [0.90579152, 0.78764708, 0.9234493 ],
       [0.34600652, 0.83650377, 0.30290443],
       [0.06853673, 0.63323188, 0.42974914],
       [0.84663749, 0.23530503, 0.09188395],
       [0.50845913, 0.34194832, 0.8160888 ],
       [0.44933202, 0.26925193, 0.030636  ],
       [0.26759541, 0.10222585, 0.74833449],
       [0.94246355, 0.53723729, 0.87895033],
       [0.62484164, 0.74323739, 0.5470341 ],
       [0.94904421, 0.42666833, 0.4789563 ],
       [0.99630634, 0.12675149, 0.34994853],
       [0.21517363, 0.7432856 , 0.91692653],
       [0.02811157, 0.7540698 , 0.98572066],
       [0.17063745, 0.05906372, 0.4386854 ],
       [0.43418579, 0.91934571, 0.0401332 ],
       [0.07264353, 0.83119658, 0.90928475],
       [0.

In [12]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1], data[c2]])
clust_centers

array([[0.07264353, 0.83119658, 0.90928475],
       [0.43882079, 0.28282488, 0.82016433]])

In [9]:
from scipy.cluster.vq import vq

In [13]:
vq(data, clust_centers)

(array([1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0,
        1, 1, 0, 1, 0, 0, 1, 1]),
 array([0.91539641, 0.942776  , 0.63714055, 0.79300794, 0.50770869,
        0.        , 0.69539549, 0.66517109, 0.51880757, 0.83604122,
        0.09144228, 0.78971494, 0.25902446, 0.56730723, 0.56673059,
        0.63042985, 0.74582299, 0.16763522, 0.11736304, 0.51722098,
        0.9454668 , 0.        , 0.17817902, 0.60617642, 0.3913737 ,
        0.68335833, 0.19573393, 0.65549896, 0.52126496, 0.80397953]))

In [14]:
from scipy.cluster.vq import kmeans

In [15]:
# Acá le doy al método kmeans los centroides
kmeans(data, clust_centers)

(array([[0.28462946, 0.79813117, 0.58738443],
        [0.68372825, 0.34824796, 0.48347489]]), 0.42753399659871333)

In [16]:
# Acá e doy al método kmeans la cantidad de clusters y el generará el cluster
kmeans(data, 2)

(array([[0.73421933, 0.39460765, 0.22338613],
        [0.40617383, 0.59227012, 0.72036767]]), 0.41915596281320083)