## Linear Regression with Scikit-learn

In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_selection import RFE
from sklearn.svm import SVR

In [4]:
data = pd.read_csv("C:/Users/l_jor/OneDrive/Documents/GitHub/python-ml-course/datasets/ads/Advertising.csv")
data.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [9]:
feature_cols = ["TV","Radio","Newspaper"]

In [11]:
x = data[feature_cols]
y = data["Sales"]

In [17]:
estimator = SVR(kernel = "linear")
selector = RFE(estimator, 2, step = 1)
selector = selector.fit(x,y)

In [18]:
selector.support_

array([ True,  True, False])

In [19]:
from sklearn.linear_model import LinearRegression

In [20]:
xpred = x[["TV","Radio"]]

In [23]:
lm = LinearRegression()
lm.fit(xpred,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [24]:
lm.intercept_

array([0.04575482, 0.18799423])

In [26]:
lm.coef_

array([0.04575482, 0.18799423])

In [27]:
lm.score(xpred,y)

0.8971942610828956